#!/bin/sh

# Run linting and formatting
npm run check --write --staged --config-path config/biome.jsonc --no-errors-on-unmatched --files-ignore-unknown=true

# Run Typechecking
npm run type-check
type_check_status=$?

if [ $type_check_status -ne 0 ]; then
  echo "Typechecking failed! Please fix the errors and try committing again."
  exit $type_check_status
fi

# Ensure the script exits with success if everything passed
exit 0
